---
spring:
  config:
    activate:
      on-profile: dev

management.endpoints.web:
  exposure.include: '*'
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
management:
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always

logging:
  level:
    root: info
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
