server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          pm-client:
            provider: iam
            authorization-grant-type: authorization_code
            scope: openid, profile, user_read
            client-name: pm-client
            client-id: ${CLIENT_ID:pm-client}
            client-secret: ${CLIENT_SECRET:pm-secret}
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/{registrationId}
        provider:
          iam:
            issuer-uri: http://127.0.0.1:9000
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
