management.endpoints.web:
  exposure.include: '*'
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
management:
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always

logging:
  level:
    root: info
